### ISSUE TITLE
Create a Workspace.next prototype that separates build and runtime

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#544]
![workspace next](https://user-images.githubusercontent.com/606959/36097650-1fede67a-0ffc-11e8-814f-687d54f0dc40.jpg)

**Comment by l0rd** [comment]
- [ ] Verify perfs (user experience should not be worst than actual model, i.e. vertx hot redeploy)
- [ ] Verify that we can specify that the 2 containers will run on the same openshift node (with some affinity label)

**Comment by garagatyi** [comment]
@l0rd can you add more details to this issue? I am not aware of a discussion that produced the photo in this issue and there is no explanation on what is expected to be done in this issue.

**Comment by l0rd** [comment]
@garagatyi I think we discussed that (this issue details) on mattermost last week so please have a look at your mattermost history. If that's not enough you can ping @gorkem or @slemeur that participated to the original discussion. If you are still blocked move to another issue. I am on PTO and cannot help you more.

**Comment by garagatyi** [comment]
I checked affinity labels and they work. 
### Explanation of how to use affinity of pods:
1. Add label to dependency pod on which deployment of dependent pod will rely
```
  kind: Pod                                                                                                                                                                                                        
  metadata:                                                                                                                                                                                                        
    name: edit                                                                                                                                                                                                     
    labels:                                                                                                                                                                                                        
       affinityForWorkspace: "workspaceId123"
```
2. Add affinity configuration 
```
  kind: Pod                                                                                                                                                                                                        
  metadata:                                                                                                                                                                                                        
    name: build                                                                                                                                                                                                           
  spec:                                                                                                                                                                                                            
    affinity:                                                                                                                                                                                                      
      podAffinity:                                                                                                                                                                                                 
        requiredDuringSchedulingIgnoredDuringExecution:                                                                                                                                                            
        - labelSelector:                                                                                                                                                                                           
            matchExpressions:                                                                                                                                                                                      
            - key: affinityForWorkspace                                                                                                                                                                            
              operator: In                                                                                                                                                                                         
              values:                                                                                                                                                                                              
              - "workspaceId123"                                                                                                                                                                                   
          topologyKey: kubernetes.io/hostname
```
### Pros of affinity
1. Since mount of the same volume to several pods is local in case of affinity there is no cost on syncing, it is instantaneous, bi-directional, and doesn't reduce performance of file operations in the volume
2. Easy to use
3. Doesn't use any additional resources of infrastructure
4. In case sources belong to an interpreted language mounting them to run pod may allow instant update with page refresh or reload on change tracking technics. 

### Drawbacks of affinity
1. It appears that not all the clusters of OSO are configured to support affinity, so in case we decide to use affinity we should ensure that it is enabled everywhere we will use it 
2. We should configure pods in a way that prevents possible matching of affinity to any not related to workspace pod
3. There is a situation when affinity would not allow us to deploy dependent pod at all - when dependency pod is deployed on a node that is already full (from the resource quotas perspective). In that case, scheduling of the pod would either never end or end after some significant timeout (I didn't wait so long in my tests)
4. In case of continuous redeployment of a run pod (pretty actual for a compiled language), the problem from the previous point become much more probable.

### Other things we should consider 
Because of the issue with pods scheduling on a node with lack of resources, we might think to use another approach instead of affinity or in addition to affinity. A particular example is a 1-way syncing between volumes: all the changes from build pod appears (probably with some delay) in run pod or mountable in a newly deployed run pod.

### Here is the instruction to try affinity
Login to OS
1. `oc login ...`
Clean up project
1. `oc delete all --all`
1. `oc delete pvc --all`
Deploy test pods
1. `oc apply -f https://gist.githubusercontent.com/garagatyi/05a3bf8d0ca41ba4613e3d73e6747d4c/raw/a6f8550a2cfbe5b9ed1a994df8adf45c61a6bba7/app.yml`
Wait until `oc get pods` shows 2 pods with Running status
1. `oc get pods`
Clone vertx repo to `edit` pod in mount path
1. `oc exec edit -- sh -c 'cd /projects && git clone https://github.com/garagatyi/test.git && cd test && ls'`
Compile and run vertx app
1. `oc exec build -- sh -c 'cd /projects/test && scl enable rh-maven33 "mvn compile vertx:run"'`
Open URL of route to verify vertx webpage availability
1. `oc get routes vertx`
